# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: xenial
branches:
  only:
    - master

addons:
  apt:
    packages:
      - libxml2-dev
      - libpoppler-cpp-dev
      - libcurl4-openssl-dev
      - g++

env:
  global:
    - CXX14=g++
